export type FieldValidationCode =
    'min-str'
    | 'min-num'
    | 'max-str'
    | 'max-num'
    | 'email'
    | 'empty'
    | 'equal-to'
    | 'min-numbers'
    | 'max-numbers'
    | 'min-chars'
    | 'max-chars'
    | 'min-upper-chars'
    | 'max-upper-chars'
    | 'min-lower-chars'
    | 'max-lower-chars'
    | 'min-special-chars'
    | 'max-special-chars'
    | string
    ;